# Generated by Django 4.2.13 on 2024-06-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0003_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='X1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='X1r',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='X2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='X2r',
            field=models.FloatField(),
        ),
    ]
